export interface QueryIssueOptions {
    accept: string,
    owner: string,
    repo: string,
    milestone: string,
    state: string,
    assignee: string,
    creator: string,
    mentioned: string,
    labels: string,
    sort: string,
    direction: string,
    since: string,
    per_page: number,
    page: number,
}